name: lightSkills
version: 1.0-SNAPSHOT
main: de.lightplugins.skyblock.master.Main
api-version: 1.17
depend: [Vault]
softdepend: [PlaceholderAPI, WorldGuard, DecentHolograms]
loadbefore: []
commands:
  skills:
    description: "The main command for the plugin"
    aliases: [sk]
libraries:
  - me.devnatan:inventory-framework-platform-paper:3.1.0-rc