name: lightSkills
version: 1.0-SNAPSHOT
main: de.lightplugins.skills.master.Main
api-version: 1.17
depend: [Vault]
softdepend: [PlaceholderAPI, WorldGuard, DecentHolograms]
loadbefore: []
commands:
  skills:
    description: "The main command for the plugin"
    aliases: [sk]